CREATE TABLE legendum_dialogue (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    story_id INTEGER
        REFERENCES legendum_stories(id) ON DELETE CASCADE NOT NULL,
    page INTEGER NOT NULL UNIQUE,
    text TEXT NOT NULL,
    image TEXT,
    choices TEXT,
    responses_to_choices TEXT
);