CREATE TABLE legendum_saved_notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    hint_id INTEGER
        REFERENCES legendum_exercises_learn_hints(id) ON DELETE SET NULL,
    custom_note TEXT,
    date_modified TIMESTAMPTZ DEFAULT now() NOT NULL,
    user_id INTEGER
        REFERENCES legendum_users(id) ON DELETE CASCADE NOT NULL
);
