CREATE TABLE legendum_completed_exercises (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    exercise_id INTEGER
        REFERENCES legendum_exercises(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER
        references legendum_users(id) ON DELETE CASCADE NOT NULL,
    date_completed TIMESTAMPTZ DEFAULT now() NOT NULL
);