CREATE TABLE legendum_completed_exercises (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    chapter_number INTEGER
        REFERENCES legendum_exercises(chapter_number) ON DELETE CASCADE NOT NULL,
    user_id INTEGER
        REFERENCES legendum_users(id) ON DELETE CASCADE NOT NULL,
    date_completed TIMESTAMPTZ DEFAULT now() NOT NULL
);
