BEGIN;
TRUNCATE
    legendum_dialogue
    RESTART IDENTITY CASCADE;

SET CLIENT_ENCODING TO 'utf8';
INSERT INTO legendum_dialogue (
    chapter_number, 
    page, 
    text, 
    choices, 
    responses_to_choices, 
    image_url, 
    image_alt_text, 
    background_image_url, 
    background_image_alt_text
)
VALUES
    (1, 1, '(You wake up and find yourself in a strange place.  Before you stands a strange looking man wearing a large blanket.  Your head feels fuzzy and you have no idea where you are or how you got there.  Suddenly, the man speaks.)', null, null, 'https://lh3.googleusercontent.com/pw/ACtC-3eFOqPNGADXGNHzM1I6cdRQOpV_bLTlDVd_7c9nP11jlutDh1qy0VG-hPHzR0gyUfpeVFcDrq6VwS73OyeaNTbLWC0UcS_LfwzKWcC7J8PLI60dZaUYcjScmvd6wFoYKTAxYMaIJ7oaPufLH0pCv0dn=w480-h600-no?authuser=2', 'Man with dark hair and large beard.', 'https://lh3.googleusercontent.com/pw/ACtC-3e8egvT3TwjewgTmD9l3Gqk3xQDV0t2Sgh2mPke2hZmXkC4VeC9FoRZkEWJmrAGxm3xMBmeCgu8UNdjUlIqR_zHW_r8KqC38kb54HtymhoJ9oP_-AvKyIHED0zpXfbzDn5VlxDNw__ISSR2NSLMUWwg=w1178-h883-no?authuser=2', 'You are in a cave with a river running through the background.'),
    (1, 2, 'Rhadamanthus: “Bene advēnistī ad domum Plūtōnis.  Sum Rhadamanthus, iūdex mortuōrum.”', null, null, 'https://lh3.googleusercontent.com/pw/ACtC-3eFOqPNGADXGNHzM1I6cdRQOpV_bLTlDVd_7c9nP11jlutDh1qy0VG-hPHzR0gyUfpeVFcDrq6VwS73OyeaNTbLWC0UcS_LfwzKWcC7J8PLI60dZaUYcjScmvd6wFoYKTAxYMaIJ7oaPufLH0pCv0dn=w480-h600-no?authuser=2', 'Man with dark hair and large beard.', 'https://lh3.googleusercontent.com/pw/ACtC-3e8egvT3TwjewgTmD9l3Gqk3xQDV0t2Sgh2mPke2hZmXkC4VeC9FoRZkEWJmrAGxm3xMBmeCgu8UNdjUlIqR_zHW_r8KqC38kb54HtymhoJ9oP_-AvKyIHED0zpXfbzDn5VlxDNw__ISSR2NSLMUWwg=w1178-h883-no?authuser=2', 'You are in a cave with a river running through the background.'),
    (1, 3, '(Bemused, you stare at the man.)', null, null, 'https://lh3.googleusercontent.com/pw/ACtC-3eFOqPNGADXGNHzM1I6cdRQOpV_bLTlDVd_7c9nP11jlutDh1qy0VG-hPHzR0gyUfpeVFcDrq6VwS73OyeaNTbLWC0UcS_LfwzKWcC7J8PLI60dZaUYcjScmvd6wFoYKTAxYMaIJ7oaPufLH0pCv0dn=w480-h600-no?authuser=2', 'Man with dark hair and large beard.', 'https://lh3.googleusercontent.com/pw/ACtC-3e8egvT3TwjewgTmD9l3Gqk3xQDV0t2Sgh2mPke2hZmXkC4VeC9FoRZkEWJmrAGxm3xMBmeCgu8UNdjUlIqR_zHW_r8KqC38kb54HtymhoJ9oP_-AvKyIHED0zpXfbzDn5VlxDNw__ISSR2NSLMUWwg=w1178-h883-no?authuser=2', 'You are in a cave with a river running through the background.'),
    (1, 4, 'Rhadamanthus: “Ah, I see.  You’re one of the new kids.”', '“I’m not a kid…”|“Uhhhh, what?”', 'Rhadamanthus: “Well, I’m over 3000 years old…”|Rhadamanthus: “Why do they always say that?”', 'https://lh3.googleusercontent.com/pw/ACtC-3eFOqPNGADXGNHzM1I6cdRQOpV_bLTlDVd_7c9nP11jlutDh1qy0VG-hPHzR0gyUfpeVFcDrq6VwS73OyeaNTbLWC0UcS_LfwzKWcC7J8PLI60dZaUYcjScmvd6wFoYKTAxYMaIJ7oaPufLH0pCv0dn=w480-h600-no?authuser=2', 'Man with dark hair and large beard.', 'https://lh3.googleusercontent.com/pw/ACtC-3e8egvT3TwjewgTmD9l3Gqk3xQDV0t2Sgh2mPke2hZmXkC4VeC9FoRZkEWJmrAGxm3xMBmeCgu8UNdjUlIqR_zHW_r8KqC38kb54HtymhoJ9oP_-AvKyIHED0zpXfbzDn5VlxDNw__ISSR2NSLMUWwg=w1178-h883-no?authuser=2', 'You are in a cave with a river running through the background.'),
    (1, 5, 'Rhadamanthus: “I’m Rhadamanthus, judge of the dead, and you’re in the house of Pluto.”', '“Rhada--what?”|“...I’m dead?”', 'Rhadamanthus: “Rhadamanthus.  You know, THE Rhadamanthus…  Son of Jove, king of Crete, judge of the dead…”|“What, because you heard some Latin you must be dead?”', 'https://lh3.googleusercontent.com/pw/ACtC-3eFOqPNGADXGNHzM1I6cdRQOpV_bLTlDVd_7c9nP11jlutDh1qy0VG-hPHzR0gyUfpeVFcDrq6VwS73OyeaNTbLWC0UcS_LfwzKWcC7J8PLI60dZaUYcjScmvd6wFoYKTAxYMaIJ7oaPufLH0pCv0dn=w480-h600-no?authuser=2', 'Man with dark hair and large beard.', 'https://lh3.googleusercontent.com/pw/ACtC-3e8egvT3TwjewgTmD9l3Gqk3xQDV0t2Sgh2mPke2hZmXkC4VeC9FoRZkEWJmrAGxm3xMBmeCgu8UNdjUlIqR_zHW_r8KqC38kb54HtymhoJ9oP_-AvKyIHED0zpXfbzDn5VlxDNw__ISSR2NSLMUWwg=w1178-h883-no?authuser=2', 'You are in a cave with a river running through the background.'),
    (1, 6, 'Rhadamanthus: “You’re not dead.  You’ve been chosen for a very special task: you’re going to be a genius!”', '“I’m already a genius.”|“...chosen?”', '“If you were a genius, you would have stayed on the beach in Naples.”|“Well, in a way, you chose your own fate.”', 'https://lh3.googleusercontent.com/pw/ACtC-3eFOqPNGADXGNHzM1I6cdRQOpV_bLTlDVd_7c9nP11jlutDh1qy0VG-hPHzR0gyUfpeVFcDrq6VwS73OyeaNTbLWC0UcS_LfwzKWcC7J8PLI60dZaUYcjScmvd6wFoYKTAxYMaIJ7oaPufLH0pCv0dn=w480-h600-no?authuser=2', 'Man with dark hair and large beard.', 'https://lh3.googleusercontent.com/pw/ACtC-3e8egvT3TwjewgTmD9l3Gqk3xQDV0t2Sgh2mPke2hZmXkC4VeC9FoRZkEWJmrAGxm3xMBmeCgu8UNdjUlIqR_zHW_r8KqC38kb54HtymhoJ9oP_-AvKyIHED0zpXfbzDn5VlxDNw__ISSR2NSLMUWwg=w1178-h883-no?authuser=2', 'You are in a cave with a river running through the background.'),
    (1, 7, 'Rhadamanthus: “Maybe you fell into Lethe on your way here, but you were vacationing in Naples and decided to visit Lake Avernus without a guide.  You got lost and it started to rain quite heavily, so you made for a nearby cave.  In the dark of the cave, you tripped and stumbled all the way down to the underworld.”', '“That doesn’t sound like me.”|“If that’s true, I probably shouldn’t be CHOSEN to do anything…”', 'Rhadamanthus: “Well, you fell into Lethe, the river of forgetfulness, genius.”|Rhadamanthus: “That is why it must be you!  Sorry, we get movies a bit late down here, and I just saw Gladiator…”', 'https://lh3.googleusercontent.com/pw/ACtC-3eFOqPNGADXGNHzM1I6cdRQOpV_bLTlDVd_7c9nP11jlutDh1qy0VG-hPHzR0gyUfpeVFcDrq6VwS73OyeaNTbLWC0UcS_LfwzKWcC7J8PLI60dZaUYcjScmvd6wFoYKTAxYMaIJ7oaPufLH0pCv0dn=w480-h600-no?authuser=2', 'Man with dark hair and large beard.',  'https://lh3.googleusercontent.com/pw/ACtC-3e8egvT3TwjewgTmD9l3Gqk3xQDV0t2Sgh2mPke2hZmXkC4VeC9FoRZkEWJmrAGxm3xMBmeCgu8UNdjUlIqR_zHW_r8KqC38kb54HtymhoJ9oP_-AvKyIHED0zpXfbzDn5VlxDNw__ISSR2NSLMUWwg=w1178-h883-no?authuser=2', 'You are in a cave with a river running through the background.'),
    (1, 8, 'Rhadamanthus: “Anyway, since you’re here and you’re not technically dead, we have a very special job for you: you’re going to be assigned to a child as a genius--a guardian spirit who offers advice and guidance!  Luckily for you, we’re shorthanded in the Roman empire, so YOU get to learn Latin!  Don’t worry, I’ll help you.  Let’s start with some basics.”', null, null, 'https://lh3.googleusercontent.com/pw/ACtC-3eFOqPNGADXGNHzM1I6cdRQOpV_bLTlDVd_7c9nP11jlutDh1qy0VG-hPHzR0gyUfpeVFcDrq6VwS73OyeaNTbLWC0UcS_LfwzKWcC7J8PLI60dZaUYcjScmvd6wFoYKTAxYMaIJ7oaPufLH0pCv0dn=w480-h600-no?authuser=2', 'Man with dark hair and large beard.', 'https://lh3.googleusercontent.com/pw/ACtC-3e8egvT3TwjewgTmD9l3Gqk3xQDV0t2Sgh2mPke2hZmXkC4VeC9FoRZkEWJmrAGxm3xMBmeCgu8UNdjUlIqR_zHW_r8KqC38kb54HtymhoJ9oP_-AvKyIHED0zpXfbzDn5VlxDNw__ISSR2NSLMUWwg=w1178-h883-no?authuser=2', 'You are in a cave with a river running through the background.'),
    (2, 1, 'Rhadamanthus: “You’re off to a great start. Before you know it, you’ll be a bona fide, Latin-speaking genius!”', null, null, 'https://lh3.googleusercontent.com/pw/ACtC-3cZiSBip8xR-750z5mwfQFqk4Us8NHaR4qaVqFdkv4OIDNw3fOcHURFpApu2Ty2IA0YHoDM9aAHVZKpEsbLfnSCSggITTYA74YO0b_9WCEc0IIdks6ppwiJqXRdeBBYkfs9T0ry5JMlp6Z5lUYn8yjK=s600-no?authuser=2', 'Man with dark hair and large beard.', 'https://lh3.googleusercontent.com/pw/ACtC-3e8egvT3TwjewgTmD9l3Gqk3xQDV0t2Sgh2mPke2hZmXkC4VeC9FoRZkEWJmrAGxm3xMBmeCgu8UNdjUlIqR_zHW_r8KqC38kb54HtymhoJ9oP_-AvKyIHED0zpXfbzDn5VlxDNw__ISSR2NSLMUWwg=w1178-h883-no?authuser=2', 'You are in a cave with a river running through the background.'),
    (2, 2, 'Rhadamanthus: “In the meantime, you’ll have some help from a translator, Enni.”', null, null, 'https://lh3.googleusercontent.com/pw/ACtC-3fhVO_SsbOQlx12WNxd8OryhSs-xAhqiF84GtWQUDxD5oaZEjwsNm7drsLKFgV6tCcrhD78MzP1GtgzDzwf464_1r6SJXl4QUtkoFlJRZ2CaOs1NHD4TEygaDrY6PWL8uf8FZELpfoLkGHUY8ET1pJQ=s600-no?authuser=2', 'A dog with three heads.', 'https://lh3.googleusercontent.com/pw/ACtC-3e8egvT3TwjewgTmD9l3Gqk3xQDV0t2Sgh2mPke2hZmXkC4VeC9FoRZkEWJmrAGxm3xMBmeCgu8UNdjUlIqR_zHW_r8KqC38kb54HtymhoJ9oP_-AvKyIHED0zpXfbzDn5VlxDNw__ISSR2NSLMUWwg=w1178-h883-no?authuser=2', 'You are in a cave with a river running through the background.'),
    (2, 3, 'Rhadamanthus: “Enni here—with his three heads and three tongues—can speak three languages, including Latin and English!  He’ll help you as you learn how to communicate with your charge.”', null, null, 'https://lh3.googleusercontent.com/pw/ACtC-3e-RqGGgkCT-0o2xE88clvCv4Urg9lkIdnyZWUxTMhr-98c3kP91GxIbq09bVPFNfcweQdXcf0jTv1F1QpnN5sAz6UQTjyvOVW5wTTgEY_13VcqhAxSPHc4Er9RW-GcjvALD7tzdMMYA-6fauo-neqW=s600-no?authuser=2', 'A man with dark hair and a beard and a three-headed dog.', 'https://lh3.googleusercontent.com/pw/ACtC-3e8egvT3TwjewgTmD9l3Gqk3xQDV0t2Sgh2mPke2hZmXkC4VeC9FoRZkEWJmrAGxm3xMBmeCgu8UNdjUlIqR_zHW_r8KqC38kb54HtymhoJ9oP_-AvKyIHED0zpXfbzDn5VlxDNw__ISSR2NSLMUWwg=w1178-h883-no?authuser=2', 'You are in a cave with a river running through the background.'),
    (2, 4, 'Rhadamanthus: “Now I’m going to send you back in time. I’d tell you where and when, but I’d hate to deprive you of the chance to figure that out for yourself.”', null, null, 'https://lh3.googleusercontent.com/pw/ACtC-3e-RqGGgkCT-0o2xE88clvCv4Urg9lkIdnyZWUxTMhr-98c3kP91GxIbq09bVPFNfcweQdXcf0jTv1F1QpnN5sAz6UQTjyvOVW5wTTgEY_13VcqhAxSPHc4Er9RW-GcjvALD7tzdMMYA-6fauo-neqW=s600-no?authuser=2', 'A man with dark hair and a beard and a three-headed dog.', 'https://lh3.googleusercontent.com/pw/ACtC-3e8egvT3TwjewgTmD9l3Gqk3xQDV0t2Sgh2mPke2hZmXkC4VeC9FoRZkEWJmrAGxm3xMBmeCgu8UNdjUlIqR_zHW_r8KqC38kb54HtymhoJ9oP_-AvKyIHED0zpXfbzDn5VlxDNw__ISSR2NSLMUWwg=w1178-h883-no?authuser=2', 'You are in a cave with a river running through the background.'),
    (2, 5, 'Rhadamanthus: “Your job will be to guide your child and offer advice.  Enni will always be there for you, but the more Latin you learn, the better genius you’ll be!  Who knows: maybe I’ll have some more jobs for you in the future!  Bona fortūna!”', null, null, 'https://lh3.googleusercontent.com/pw/ACtC-3e-RqGGgkCT-0o2xE88clvCv4Urg9lkIdnyZWUxTMhr-98c3kP91GxIbq09bVPFNfcweQdXcf0jTv1F1QpnN5sAz6UQTjyvOVW5wTTgEY_13VcqhAxSPHc4Er9RW-GcjvALD7tzdMMYA-6fauo-neqW=s600-no?authuser=2', 'A man with dark hair and a beard and a three-headed dog.', 'https://lh3.googleusercontent.com/pw/ACtC-3e8egvT3TwjewgTmD9l3Gqk3xQDV0t2Sgh2mPke2hZmXkC4VeC9FoRZkEWJmrAGxm3xMBmeCgu8UNdjUlIqR_zHW_r8KqC38kb54HtymhoJ9oP_-AvKyIHED0zpXfbzDn5VlxDNw__ISSR2NSLMUWwg=w1178-h883-no?authuser=2', 'You are in a cave with a river running through the background.'),
    (2, 6, '(The room spins and you lose consciousness for a moment….)', null, null, null, null, 'https://lh3.googleusercontent.com/pw/ACtC-3cbP5KtqVhkFcrXwmYS9NaJq3BFgO-t_pFPnObm0NAGN4A-u6JPex-7Y_7N2HoH7PT_wVO50l3tYjL5Hfa_bXHqsn0UEcusOWXedYcPYkCAxJ20mL7y_u7TIEYWHiKKGRF_m_GUCxEmtVVBmZCrmHIW=s600-no?authuser=2', 'A swirl of lights.'),
    (2, 7, '(When the spinning stops you find yourself in a small room with a small child.)', null, null, 'https://lh3.googleusercontent.com/pw/ACtC-3diuQRbzVEXrr7diMtVwZuqhCMGkSVBVoRBBFq8wHSgeG4-wWSv3Icj5_T9Ztv_BDI80vldBncJ0L67V7VHdLhcGKX7DyPKJVoRbEEU-fp6KKRIhRRGYGcUS9xuWJ_TfJnJ_IhpQ_VduWB4LdXHQRVJ=s600-no?authuser=2', 'A small child sits holding a scroll.', 'https://lh3.googleusercontent.com/pw/ACtC-3c56GTnSjywKqHobOBYnFDsEU-wiD9n5EQ_uk_ChYNihApwfyvtBTfonPSz9VvjOpLHyD7_0WZEEOMOG5NsmtEYyvX0ybl3SZ3AQTsoXLqE5KSEF4eePQLMswF0qq1dPjHT0mvzFahgXXQKnUEgiq11=w1178-h883-no?authuser=2', 'You are in a typical Roman room with a decorated floor and painted walls.'),
    (2, 8, 'Enni: “Here we are! Maybe we shouldn’t reveal ourselves right away. It might be better to whisper some insight into the child’s ear until he gets used to our presence.”', null, null, 'https://lh3.googleusercontent.com/pw/ACtC-3f38Qk12IW1k-aY44KzNk1GbonPx88KmY4XjQgyPfDmWGvDS6sC0Wb2V1Sjdtd1xPZ_8bsKOHPaaQzanDMAs1QLBUZcCmqImI-Ne3Sru65E8tZahnKe9ShJKehb9zRaH1qHAjdlgUrWmqC_EalAwCJ7=s600-no?authuser=0', 'A small boy sits holding a scroll; a three-headed dog sits besdie him.', 'https://lh3.googleusercontent.com/pw/ACtC-3c56GTnSjywKqHobOBYnFDsEU-wiD9n5EQ_uk_ChYNihApwfyvtBTfonPSz9VvjOpLHyD7_0WZEEOMOG5NsmtEYyvX0ybl3SZ3AQTsoXLqE5KSEF4eePQLMswF0qq1dPjHT0mvzFahgXXQKnUEgiq11=w1178-h883-no?authuser=2', 'You are in a typical Roman room with a decorated floor and painted walls.'),
    (2, 9, 'Enni: “Hmmm, I smell homework! Looks like the child is studying geography. This is the perfect chance to brush up on your own geography skills and learn some more Latin! Then, you can help the child and, if all goes well, reveal yourself!”', null, null, 'https://lh3.googleusercontent.com/pw/ACtC-3f38Qk12IW1k-aY44KzNk1GbonPx88KmY4XjQgyPfDmWGvDS6sC0Wb2V1Sjdtd1xPZ_8bsKOHPaaQzanDMAs1QLBUZcCmqImI-Ne3Sru65E8tZahnKe9ShJKehb9zRaH1qHAjdlgUrWmqC_EalAwCJ7=s600-no?authuser=0', 'A small boy sits holding a scroll; a three-headed dog sits besdie him.', 'https://lh3.googleusercontent.com/pw/ACtC-3c56GTnSjywKqHobOBYnFDsEU-wiD9n5EQ_uk_ChYNihApwfyvtBTfonPSz9VvjOpLHyD7_0WZEEOMOG5NsmtEYyvX0ybl3SZ3AQTsoXLqE5KSEF4eePQLMswF0qq1dPjHT0mvzFahgXXQKnUEgiq11=w1178-h883-no?authuser=2', 'You are in a typical Roman room with a decorated floor and painted walls.');

COMMIT;