BEGIN;

TRUNCATE
    legendum_exercises_learn
    RESTART IDENTITY CASCADE;

SET CLIENT_ENCODING to 'utf8';

INSERT INTO legendum_exercises_learn (chapter_number, page, text, image_url, image_alt_text, background_image_url, background_image_alt_text)
VALUES
    (1, 1, 'Lūcius: “Salvē!”', 'https://res.cloudinary.com/legendum/image/upload/v1602251514/intro_learn_lucius_talking_khc6to.png', 'A man named Lucius speaks to a woman named Iulia.', 'https://res.cloudinary.com/legendum/image/upload/v1602251514/Countryside_small_a22a4h.jpg', 'A sunny day in the Italian countryside.'),
    (1, 2, 'Lūcius: “Egō sum Lūcius!”', 'https://res.cloudinary.com/legendum/image/upload/v1602251514/intro_learn_lucius_talking_khc6to.png', 'A man named Lucius speaks to a woman named Iulia.', 'https://res.cloudinary.com/legendum/image/upload/v1602251514/Countryside_small_a22a4h.jpg', 'A sunny day in the Italian countryside.'),
    (1, 3, 'Lūcius: “Nōmen mihi est Lūcius!”', 'https://res.cloudinary.com/legendum/image/upload/v1602251514/intro_learn_lucius_talking_khc6to.png', 'A man named Lucius speaks to a woman named Iulia.', 'https://res.cloudinary.com/legendum/image/upload/v1602251514/Countryside_small_a22a4h.jpg', 'A sunny day in the Italian countryside.'),
    (1, 4, 'Iūlia: “Salvē, Lūcī!”', 'https://res.cloudinary.com/legendum/image/upload/v1602251514/intro_learn_iulia_talking_fuyoq2.png', 'A woman named Iulia speaks to a man named Lucius.', 'https://res.cloudinary.com/legendum/image/upload/v1602251514/Countryside_small_a22a4h.jpg', 'A sunny day in the Italian countryside.'),
    (1, 5, 'Lūcius: “Quid est nōmen tibi?”', 'https://res.cloudinary.com/legendum/image/upload/v1602251514/intro_learn_lucius_talking_khc6to.png', 'A man named Lucius speaks to a woman named Iulia.', 'https://res.cloudinary.com/legendum/image/upload/v1602251514/Countryside_small_a22a4h.jpg', 'A sunny day in the Italian countryside.'),
    (1, 6, 'Iūlia: “Nōmen mihi est Iūlia.  Ego sum Iūlia.”', 'https://res.cloudinary.com/legendum/image/upload/v1602251514/intro_learn_iulia_talking_fuyoq2.png', 'A woman named Iulia speaks to a man named Lucius.', 'https://res.cloudinary.com/legendum/image/upload/v1602251514/Countryside_small_a22a4h.jpg', 'A sunny day in the Italian countryside.'),
    (1, 7, 'Lūcius: “Salvē, Iūlia! Pergrātum tē convenīre!”', 'https://res.cloudinary.com/legendum/image/upload/v1602251514/intro_learn_lucius_talking_khc6to.png', 'A man named Lucius speaks to a woman named Iulia.', 'https://res.cloudinary.com/legendum/image/upload/v1602251514/Countryside_small_a22a4h.jpg', 'A sunny day in the Italian countryside.'),
    (1, 8, 'Iūlia: “Pergrātum quoque tē convenīre!”', 'https://res.cloudinary.com/legendum/image/upload/v1602251514/intro_learn_iulia_talking_fuyoq2.png', 'A woman named Iulia speaks to a man named Lucius.', 'https://res.cloudinary.com/legendum/image/upload/v1602251514/Countryside_small_a22a4h.jpg', 'A sunny day in the Italian countryside.'),
    (1, 9, 'Lūcius et Iūlia: “Valē!”', 'https://res.cloudinary.com/legendum/image/upload/v1602251515/intro_learn_names_dunia7.png', 'Lucius and Iulia speak at the same time.', 'https://res.cloudinary.com/legendum/image/upload/v1602251514/Countryside_small_a22a4h.jpg', 'A sunny day in the Italian countryside.'),
    (1, 10, '(Lūcius exit.)', 'https://res.cloudinary.com/legendum/image/upload/v1602251515/intro_learn_lucius_exit_zl8e81.png', 'Lucius leaves and Iulia remains.', 'https://res.cloudinary.com/legendum/image/upload/v1602251514/Countryside_small_a22a4h.jpg', 'A sunny day in the Italian countryside.'),
    (1, 11, '(Iūlia exit.)', null, null, 'https://res.cloudinary.com/legendum/image/upload/v1602251514/Countryside_small_a22a4h.jpg', 'A sunny day in the Italian countryside.'),
    (2, 1, 'Haec est Rōma.', 'https://res.cloudinary.com/legendum/image/upload/v1602251590/Chapter%202%20Do%20Images/Roma_pbdvft.png', 'Map of Italy with Rome circled.', 'https://res.cloudinary.com/legendum/image/upload/v1602251515/Room1_small_pcyxdp.jpg', 'You are in a typical Roman room with a decorated floor and painted walls.'),
    (2, 2, 'Haec est Italia.', 'https://res.cloudinary.com/legendum/image/upload/v1602251590/Chapter%202%20Do%20Images/Italia_u4bdhs.png', 'Map of Europe with Italy circled.', 'https://res.cloudinary.com/legendum/image/upload/v1602251515/Room1_small_pcyxdp.jpg', 'You are in a typical Roman room with a decorated floor and painted walls.'),
    (2, 3, 'Italia est in Eurōpā.', 'https://res.cloudinary.com/legendum/image/upload/v1602251590/Chapter%202%20Do%20Images/Italia_u4bdhs.png', 'Map of Europe with Italy circled.', 'https://res.cloudinary.com/legendum/image/upload/v1602251515/Room1_small_pcyxdp.jpg', 'You are in a typical Roman room with a decorated floor and painted walls.'),
    (2, 4, 'Rōma in Italiā est.', 'https://res.cloudinary.com/legendum/image/upload/v1602251590/Chapter%202%20Do%20Images/Roma_pbdvft.png', 'Map of Italy with Rome circled.', 'https://res.cloudinary.com/legendum/image/upload/v1602251515/Room1_small_pcyxdp.jpg', 'You are in a typical Roman room with a decorated floor and painted walls.'),
    (2, 5, 'Haec est Hispānia.', 'https://res.cloudinary.com/legendum/image/upload/v1602251589/Chapter%202%20Do%20Images/Hispania_rku1ai.png', 'Map of Europe with Spain circled.', 'https://res.cloudinary.com/legendum/image/upload/v1602251515/Room1_small_pcyxdp.jpg', 'You are in a typical Roman room with a decorated floor and painted walls.'),
    (2, 6, 'Hispānia est in Eurōpā.', 'https://res.cloudinary.com/legendum/image/upload/v1602251589/Chapter%202%20Do%20Images/Hispania_rku1ai.png', 'Map of Europe with Spain circled.', 'https://res.cloudinary.com/legendum/image/upload/v1602251515/Room1_small_pcyxdp.jpg', 'You are in a typical Roman room with a decorated floor and painted walls.'),
    (2, 7, 'Haec est Graecia.', 'https://res.cloudinary.com/legendum/image/upload/v1602251589/Chapter%202%20Do%20Images/Graecia_irwyyd.png', 'Map of Europe with Greece circled.', 'https://res.cloudinary.com/legendum/image/upload/v1602251515/Room1_small_pcyxdp.jpg', 'You are in a typical Roman room with a decorated floor and painted walls.'),
    (2, 8, 'Graecia quoque in Eurōpā est.', 'https://res.cloudinary.com/legendum/image/upload/v1602251589/Chapter%202%20Do%20Images/Graecia_irwyyd.png', 'Map of Europe with Greece circled.', 'https://res.cloudinary.com/legendum/image/upload/v1602251515/Room1_small_pcyxdp.jpg', 'You are in a typical Roman room with a decorated floor and painted walls.'),
    (2, 9, 'Hispānia et Italia et Graecia in Eurōpā sunt.', 'https://res.cloudinary.com/legendum/image/upload/v1602251589/Chapter%202%20Do%20Images/Hispania_Italia_Graecia_ya5xj8.png', 'Map of Europe with Spain, Italy, and Greece circled.', 'https://res.cloudinary.com/legendum/image/upload/v1602251515/Room1_small_pcyxdp.jpg', 'You are in a typical Roman room with a decorated floor and painted walls.'),
    (2, 10, 'Hīc est Aegyptus.', 'https://res.cloudinary.com/legendum/image/upload/v1602251589/Chapter%202%20Do%20Images/Aegyptus_rlovgz.png', 'Map with Egypt circled.', 'https://res.cloudinary.com/legendum/image/upload/v1602251515/Room1_small_pcyxdp.jpg', 'You are in a typical Roman room with a decorated floor and painted walls.'),
    (2, 11, 'Aegyptus est in Āfricā.', 'https://res.cloudinary.com/legendum/image/upload/v1602251589/Chapter%202%20Do%20Images/Aegyptus_rlovgz.png', 'Map with Egypt circled.', 'https://res.cloudinary.com/legendum/image/upload/v1602251515/Room1_small_pcyxdp.jpg', 'You are in a typical Roman room with a decorated floor and painted walls.'),
    (2, 12, 'Haec est Gallia.', 'https://res.cloudinary.com/legendum/image/upload/v1602251589/Chapter%202%20Do%20Images/Gallia_gytp24.png', 'Map of Europe with Gaul circled.', 'https://res.cloudinary.com/legendum/image/upload/v1602251515/Room1_small_pcyxdp.jpg', 'You are in a typical Roman room with a decorated floor and painted walls.'),
    (2, 13, 'Gallia nōn in Āfricā sed in Eurōpā est.', 'https://res.cloudinary.com/legendum/image/upload/v1602251589/Chapter%202%20Do%20Images/Gallia_gytp24.png', 'Map of Europe with Gaul circled.', 'https://res.cloudinary.com/legendum/image/upload/v1602251515/Room1_small_pcyxdp.jpg', 'You are in a typical Roman room with a decorated floor and painted walls.'),
    (2, 14, 'Syria et Arabia nōn in Eurōpā aut in Āfricā sed in Asiā sunt.', 'https://res.cloudinary.com/legendum/image/upload/v1602251590/Chapter%202%20Do%20Images/Syria_Arabia_vx1t1q.png', 'Map with Syria and Arabia circled.', 'https://res.cloudinary.com/legendum/image/upload/v1602251515/Room1_small_pcyxdp.jpg', 'You are in a typical Roman room with a decorated floor and painted walls.');

COMMIT;
